apiVersion: v1
kind: Pod
metadata:
  name: gce-jenkins-pod
  labels:
    name: gce-jenkins-pod
spec:
  containers:
    - name: gce-jenkins
      image: docker.io/blacklabelops/jenkins
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          targetPort: 8080
        - containerPort: 50000
          targetPort: 50000
      env:
        - name: JENKINS_ADMIN_USER
          value: jenkins
        - name: JENKINS_ADMIN_PASSWORD
          value: swordfish
        - name: JENKINS_PLUGINS
          value: git hipchat swarm
        - name: JENKINS_SLAVEPORT
          value: "50000"
        - name: JAVA_VM_PARAMETERS
          value: -Xmx1024m -Xms256m
      volumeMounts:
        - name: jenkins-master-persistent-storage
          mountPath: /jenkins
  volumes:
      - name: jenkins-master-persistent-storage
        gcePersistentDisk:
          pdName: gce-jenkins-disk
          fsType: ext4
  restartPolicy: Always
  dnsPolicy: Default
