apiVersion: v1
kind: Service
metadata:
  name: gce-jenkins-service
  labels:
    name: gce-jenkins-service
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: jenkins-https
      protocol: TCP
      name: https
    - port: 50000
      targetPort: jenkins-slave
      protocol: TCP
      name: slave-port
  selector:
    name: gce-jenkins-pod
