apiVersion: v1
kind: Service
metadata:
  name: gce-jenkins-service
  labels:
    name: gce-jenkins-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: gce-jenkins-pod
